### ISSUE TITLE
Error on deploying the Zion service with docker compose

### ISSUE THREAD

**Issue by efotopoulou** [vaimee/zion#63]
hi all,

I am trying to deploy via docker compose the zion service. It seems that the environmental variable
`ZION_DB_HOST=host.docker.internal` is not understood.
Similarly the .env file is not found by the service.
```
[+] Running 2/2
 ⠿ Container zion-postgres-dev  Recreated                                                                                       0.4s
 ⠿ Container zion               Recreated                                                                                       0.0s
Attaching to zion, zion-postgres-dev
zion-postgres-dev  | 
zion-postgres-dev  | PostgreSQL Database directory appears to contain a database; Skipping initialization
zion-postgres-dev  | 
zion-postgres-dev  | 2023-06-27 08:33:02.092 UTC [1] LOG:  starting PostgreSQL 14.3 on x86_64-pc-linux-musl, compiled by gcc (Alpine 11.2.1_git20220219) 11.2.1 20220219, 64-bit
zion-postgres-dev  | 2023-06-27 08:33:02.092 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
zion-postgres-dev  | 2023-06-27 08:33:02.092 UTC [1] LOG:  listening on IPv6 address "::", port 5432
zion-postgres-dev  | 2023-06-27 08:33:02.098 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
zion-postgres-dev  | 2023-06-27 08:33:02.108 UTC [21] LOG:  database system was shut down at 2023-06-27 08:33:01 UTC
zion-postgres-dev  | 2023-06-27 08:33:02.113 UTC [1] LOG:  database system is ready to accept connections
zion               | 
zion               | > @vaimee/zion@1.0.0-alpha.3 db:migrate:latest
zion               | > knex migrate:latest
zion               | 
zion               | Requiring external module ts-node/register
zion               | [dotenv@16.0.3][DEBUG] Failed to load /home/node/app/.env ENOENT: no such file or directory, open '/home/node/app/.env'
zion               | getaddrinfo ENOTFOUND host.docker.internal
zion               | Error: getaddrinfo ENOTFOUND host.docker.internal
zion               |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)
zion               | npm notice 
zion               | npm notice New minor version of npm available! 9.5.1 -> 9.7.2
zion               | npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.7.2>
zion               | npm notice Run `npm install -g npm@9.7.2` to update!
zion               | npm notice 
zion exited with code 1
```

I am trying to deploy zion to a  Ubuntu 22.04.1 LTS machine,

Any idea is more than welcome!
Thank you so much for your time and support!

**Comment by relu91** [comment]
Hi! Thank you for using Zion and sorry for closing the issue 😄 . Sadly `host.docker.internal` is not supported on Linux machines. Can I ask you to share the docker-compose that you are using? 

> Similarly the .env file is not found by the service.

That should be fine when deploying the service with docker-compose it will use the .envs loaded by Docker not the ones inside the container.

**Comment by efotopoulou** [comment]
Hi relu91!
Thank you sooo much for your quick response!
This is my docker-compose file. It is the one given by the repo. I have changed nothing.
```
version: '3.6'
services:
  database:
    image: postgres:14.3-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=zion
    container_name: 'zion-postgres-dev'
    ports:
      - '54310:5432'
  zion:
    build: .
    depends_on:
      - database
    entrypoint: ['sh', '-c','npm run db:migrate:latest && npm run start:prod']
    ports: 
      - 3000:3000
    container_name: zion
    environment:
      - ZION_NODE_ENV
      - ZION_SERVER_PORT
      - ZION_DB_HOST=host.docker.internal
      - ZION_DB_PORT
      - ZION_DB_USER
      - ZION_DB_PASSWORD
      - ZION_DB_DATABASE
      - ZION_JWT_SECRET
      - ZION_JWT_EXPIRES_IN
```
Regarding the .env file i thing it should be copied at the /home/node/app/.env as the following Dockerfile describes. (Again is the source Dockerfile, i have changed nothing)
```
FROM node:lts-alpine as build

WORKDIR /home/node/app

COPY . .

RUN npm ci && npm run build

# ---

FROM node:lts-alpine

WORKDIR /home/node/app

COPY --from=build /home/node/app/package*.json ./
COPY --from=build /home/node/app/node_modules ./node_modules/
COPY --from=build /home/node/app/dist/ ./dist/
COPY --from=build /home/node/app/knexfile.ts ./
COPY --from=build /home/node/app/migrations ./migrations
COPY --from=build /home/node/app/static ./static

EXPOSE 3000
ENTRYPOINT ["npm", "run", "start:prod" ]
```
Any idea on how i could declare the ZION_DB_HOST in a linux based machine?

**Comment by relu91** [comment]
Thank you for providing more info! 

> Any idea on how i could declare the ZION_DB_HOST in a linux based machine?

I think that in this case, we could fix it by simply assigning the container name: `ZION_DB_HOST=database`. I assume you are testing in a dev environment. For production is better to use: `ZION_DB_HOST=tasks.database` as explained in the [Readme](https://github.com/vaimee/zion#docker-compose). 

>Regarding the .env file i think it should be copied at the /home/node/app/.env as the following Dockerfile describes. (Again is the source Dockerfile, i have changed nothing)

No, it is not. As you can see it is a two stages build image. We are not copying `.env` file in the second stage, this is on purpose cause we should have default values in Zion and not in the `.env` file. Any reason why you would like to have the .env file inside the container?

**Comment by efotopoulou** [comment]
There is no reason to have the .env file inside the container. I just want to deploy zion so to check out the APIs it supports and have a hands on experience. 

I am trying both ways to deploy it. Both within the docker and directly through npm start.
I changed the ZION_DB_HOST to database as you propose me. Things are better but still the service is not deployed. Here are the logs i get.
```
Attaching to zion, zion-postgres-testing
zion-postgres-testing  | The files belonging to this database system will be owned by user "postgres".
zion-postgres-testing  | This user must also own the server process.
zion-postgres-testing  | 
zion-postgres-testing  | The database cluster will be initialized with locale "en_US.utf8".
zion-postgres-testing  | The default database encoding has accordingly been set to "UTF8".
zion-postgres-testing  | The default text search configuration will be set to "english".
zion-postgres-testing  | 
zion-postgres-testing  | Data page checksums are disabled.
zion-postgres-testing  | 
zion-postgres-testing  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
zion-postgres-testing  | creating subdirectories ... ok
zion-postgres-testing  | selecting dynamic shared memory implementation ... posix
zion-postgres-testing  | selecting default max_connections ... 100
zion-postgres-testing  | selecting default shared_buffers ... 128MB
zion-postgres-testing  | selecting default time zone ... UTC
zion-postgres-testing  | creating configuration files ... ok
zion-postgres-testing  | running bootstrap script ... ok
zion-postgres-testing  | sh: locale: not found
zion-postgres-testing  | 2023-06-27 11:21:49.701 UTC [30] WARNING:  no usable system locales were found
zion                   | 
zion                   | > @vaimee/zion@1.0.0-alpha.3 db:migrate:latest
zion                   | > knex migrate:latest
zion                   | 
zion-postgres-testing  | performing post-bootstrap initialization ... ok
zion-postgres-testing  | syncing data to disk ... ok
zion-postgres-testing  | 
zion-postgres-testing  | 
zion-postgres-testing  | Success. You can now start the database server using:
zion-postgres-testing  | 
zion-postgres-testing  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
zion-postgres-testing  | 
zion-postgres-testing  | initdb: warning: enabling "trust" authentication for local connections
zion-postgres-testing  | You can change this by editing pg_hba.conf or using the option -A, or
zion-postgres-testing  | --auth-local and --auth-host, the next time you run initdb.
zion-postgres-testing  | waiting for server to start....2023-06-27 11:21:50.067 UTC [36] LOG:  starting PostgreSQL 14.3 on x86_64-pc-linux-musl, compiled by gcc (Alpine 11.2.1_git20220219) 11.2.1 20220219, 64-bit
zion-postgres-testing  | 2023-06-27 11:21:50.070 UTC [36] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
zion-postgres-testing  | 2023-06-27 11:21:50.080 UTC [37] LOG:  database system was shut down at 2023-06-27 11:21:49 UTC
zion-postgres-testing  | 2023-06-27 11:21:50.084 UTC [36] LOG:  database system is ready to accept connections
zion-postgres-testing  |  done
zion-postgres-testing  | server started
zion                   | Requiring external module ts-node/register
zion-postgres-testing  | CREATE DATABASE
zion-postgres-testing  | 
zion-postgres-testing  | 
zion-postgres-testing  | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
zion-postgres-testing  | 
zion-postgres-testing  | waiting for server to shut down....2023-06-27 11:21:50.251 UTC [36] LOG:  received fast shutdown request
zion-postgres-testing  | 2023-06-27 11:21:50.254 UTC [36] LOG:  aborting any active transactions
zion-postgres-testing  | 2023-06-27 11:21:50.255 UTC [36] LOG:  background worker "logical replication launcher" (PID 43) exited with exit code 1
zion-postgres-testing  | 2023-06-27 11:21:50.255 UTC [38] LOG:  shutting down
zion-postgres-testing  | 2023-06-27 11:21:50.278 UTC [36] LOG:  database system is shut down
zion-postgres-testing  |  done
zion-postgres-testing  | server stopped
zion-postgres-testing  | 
zion-postgres-testing  | PostgreSQL init process complete; ready for start up.
zion-postgres-testing  | 
zion-postgres-testing  | 2023-06-27 11:21:50.367 UTC [1] LOG:  starting PostgreSQL 14.3 on x86_64-pc-linux-musl, compiled by gcc (Alpine 11.2.1_git20220219) 11.2.1 20220219, 64-bit
zion-postgres-testing  | 2023-06-27 11:21:50.367 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
zion-postgres-testing  | 2023-06-27 11:21:50.367 UTC [1] LOG:  listening on IPv6 address "::", port 5432
zion-postgres-testing  | 2023-06-27 11:21:50.373 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
zion-postgres-testing  | 2023-06-27 11:21:50.379 UTC [50] LOG:  database system was shut down at 2023-06-27 11:21:50 UTC
zion-postgres-testing  | 2023-06-27 11:21:50.384 UTC [1] LOG:  database system is ready to accept connections
zion                   | [dotenv@16.0.3][DEBUG] Failed to load /home/node/app/.env ENOENT: no such file or directory, open '/home/node/app/.env'
zion                   | connect ECONNREFUSED 172.21.0.2:54310
zion                   | Error: connect ECONNREFUSED 172.21.0.2:54310
zion                   |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
zion                   | npm notice 
zion                   | npm notice New minor version of npm available! 9.5.1 -> 9.7.2
zion                   | npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.7.2>
zion                   | npm notice Run `npm install -g npm@9.7.2` to update!
zion                   | npm notice 
zion exited with code 1
zion-postgres-testing  | 2023-06-27 11:23:25.504 UTC [58] LOG:  invalid length of startup packet
zion-postgres-testing  | 2023-06-27 11:23:26.522 UTC [59] LOG:  invalid length of startup packet
zion-postgres-testing  | 2023-06-27 11:23:26.525 UTC [60] LOG:  invalid length of startup packet
zion-postgres-testing  | 2023-06-27 11:29:38.538 UTC [1] LOG:  received fast shutdown request
zion-postgres-testing  | 2023-06-27 11:29:38.541 UTC [1] LOG:  aborting any active transactions
zion-postgres-testing  | 2023-06-27 11:29:38.542 UTC [1] LOG:  background worker "logical replication launcher" (PID 56) exited with exit code 1
zion-postgres-testing  | 2023-06-27 11:29:38.542 UTC [51] LOG:  shutting down
zion-postgres-testing  | 2023-06-27 11:29:38.557 UTC [1] LOG:  database system is shut down
zion-postgres-testing exited with code 0
```
It seems that the zion container does not "see/discover" the database container.

From the other side when i try to install it with the commands of npm i get the following error upon executing the command `npm start`:
npm start
```

> @vaimee/zion@1.0.0-alpha.3 start /home/eleni/Documents/PythonProjects/zion
> nest start

Error: Cannot find module 'node:path'
Require stack:
- /home/eleni/Documents/PythonProjects/zion/dist/src/common/utils/env-loader.js
- /home/eleni/Documents/PythonProjects/zion/dist/src/common/utils/index.js
- /home/eleni/Documents/PythonProjects/zion/dist/src/config/config.module.js
- /home/eleni/Documents/PythonProjects/zion/dist/src/persistence/persistence.module.js
- /home/eleni/Documents/PythonProjects/zion/dist/src/api-reference/events/events.module.js
- /home/eleni/Documents/PythonProjects/zion/dist/src/api-reference/api-reference.module.js
- /home/eleni/Documents/PythonProjects/zion/dist/src/app.module.js
- /home/eleni/Documents/PythonProjects/zion/dist/src/app-factory.js
- /home/eleni/Documents/PythonProjects/zion/dist/src/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/eleni/Documents/PythonProjects/zion/src/common/utils/env-loader.ts:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @vaimee/zion@1.0.0-alpha.3 start: `nest start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @vaimee/zion@1.0.0-alpha.3 start script.
```
Which npm version do you use? In my case i use the v14.15.1. It seems to be a nvm versioning issue...
Thanks again for you support!
Zion seems a very promising software and i would really like to be able to deploy it and use it!

**Comment by relu91** [comment]
Sorry, my bad, when a service exposes the port is not reachable using the Docker internal DNS anymore (probably because it uses a different network strategy). You have two options:
1. Try to make `host.docker.internal` with Linux. There is an excellent answer on [Stackoverflow](https://stackoverflow.com/a/62431165/925955). Don't forget to change the `docker-compose.yml` by adding `extra_hosts` as pointed [here](https://stackoverflow.com/questions/48546124/what-is-linux-equivalent-of-host-docker-internal/67158212#67158212). 
2. Quick workaround. Leave everything as it is now and don't expose postgres ports:
```
version: '3.6'
services:
  database:
    image: postgres:14.3-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=zion
    container_name: 'zion-postgres-dev'
  zion:
    build: .
    depends_on:
      - database
    entrypoint: ['sh', '-c','npm run db:migrate:latest && npm run start:prod']
    ports: 
      - 3000:3000
    container_name: zion
    environment:
      - ZION_NODE_ENV
      - ZION_SERVER_PORT
      - ZION_DB_HOST=database
      - ZION_DB_PORT=5432
      - ZION_DB_USER
      - ZION_DB_PASSWORD
      - ZION_DB_DATABASE
      - ZION_JWT_SECRET
      - ZION_JWT_EXPIRES_IN
 ```
 
 Sorry, I don't have a Linux machine atm so I can't test these two options myself. Let me know whether one of the two works, I'll update the README with the instructions.

**Comment by relu91** [comment]
About `npm start`, we are using v16 but soon we will move to v18 (which should be the current LTS). Let me know if moving to v16 solves your `Cannot find module 'node:path'` error. 

> Thanks again for you support!
Zion seems a very promising software and i would really like to be able to deploy it and use it!

Thank you again for the very kind words and the feedback. For us is very valuable! Actually, I should apologize for this first-run inconvenience.

**Comment by efotopoulou** [comment]
Hi again!
Thank you so much for the clarification. Installing V16 worked like a charm. 
Same happened with the instructions for slightly updating the docker compose for Linux. It also worked for me!
It would help to mention the nvm version in the Readme file. 

Now i am trying to correct configure the postgresql on the development mode. It would help if you also put some instructions or even some extrernal links to the readme file in case(like me) there is no familiarization with postgresql. However, the truth is that posqresql set up is something external from the zion repository.

Below i pasted the message i get from the zion server. It is up and running but can not get connected to the db.
```
Thing Description Directory is active on http://localhost:3000
[Nest] 77352  - 06/27/2023, 4:51:54 PM   ERROR [ExceptionsHandler] connect ECONNREFUSED 127.0.0.1:54310
Error: connect ECONNREFUSED 127.0.0.1:54310
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
```

Wish you the best and thank you so much for your support!

**Comment by relu91** [comment]
Hey! Let's face it our documentation and configuration were not that great. We updated the README using your feedback. Can I ask you to use the new docker-compose file? Just pull the latest changes and clean up your docker-compose stacks. (see https://github.com/vaimee/zion/commit/919fceee8f3b47a0290e25eb45f5829c783cca9e)

Let us know if it works out of the box now.

**Comment by efotopoulou** [comment]
Hi Relu91!
Thank you so much for your support and feedback! It is a pleasure to have somehow contributed to your project. It is an honor really! I am out of office these days. I promise to pull the latest changes and give you my feedback on Monday the latest.
Have a nice day!

**Comment by relu91** [comment]
Thank you for your kind words! No hurries :) just let us know if we can help you further! Once it is up and running, we can also discuss missing features. 👍🏻

**Comment by relu91** [comment]
Hi, @efotopoulou any updates on this issue? let us know if we can help you!

**Comment by efotopoulou** [comment]
Hi relu91! 
Sorry for being late to respond! 
I tried the new docker-compose file and it works like a charm!
Thank you for your support!
I think this issue can be closed!

**Comment by relu91** [comment]
Thank you for opening the issue and following up 😃 . Closing.
